### ISSUE TITLE
Doesn't create S3 url's

### ISSUE THREAD

**Issue by frankkoornstra** [matt-pawley/oc-imageresizer-plugin#11]
Could you point me in the right direction regarding letting this plugin work with S3 uploads? I followed [OctoberCMS's instructions](https://octobercms.com/docs/cms/mediamanager#amazon-s3) to get the media manager to work with S3 and that's all fine.

I now have the following in my template `<img src="{{ 'image.jpg'|media|resize(200,150) }}">` but it creates a link to `<domain>/storage/app/uploads/public/68a/620/f0c/thumb__200x150_0_0_crop.jpg` where as `<img src="{{ 'image.jpg'|media }}">` points to `https://s3.eu-central-1.amazonaws.com/<bucket>/image.jpg`.

It does however create the image in the S3 bucket (after adjusting the policy in AWS IAM for that user slightly) so it's just about the URL creation. Any idea on how to make this work?

**Comment by toughdeveloper** [comment]
Hey Frank,

Thanks for using the plugin. AmazonS3 integration is currently untested although I had planned on integrating fully at some point. 

I will try get a solution together within the next week and keep you updated. 

Thanks,
Matt

**Comment by frankkoornstra** [comment]
Thanks for the rapid feedback :)

**Comment by toughdeveloper** [comment]
@frankkoornstra - Just to keep you updated, I've had a look into this and bit more complex than originally anticipated. I will still be looking to develop this feature into the plugin but due to other commitments it may not be as soon as I had hoped for. If you/anyone reading this had time to chip in I have made a start (https://github.com/toughdeveloper/oc-imageresizer-plugin/tree/v1.4.0). It currently works on files not stored of Amazon S3 (e.g. in themes/plugins directories) although files stored on s3, e.g. file uploads do not currently resize as anticipated.

**Comment by frankkoornstra** [comment]
I'm currently using another plugin that does work with S3 (https://octobercms.com/plugin/manogi-mediathumb), maybe you can see how he/she does it :) What does lack there is that it will go back to S3 every time to see if files are there. That takes up a lot of time on page load so my tip would be to anticipate on that (maybe give admins the chance to set a cache time for images or let them reload the thumbnails manually for all uploaded images and detect that) and create a better version.

**Comment by that0n3guy** [comment]
We just ran into this as well.   Using the basic getthumb() for now (https://octobercms.com/forum/post/how-to-reference-thumbnail-image-from-file-upload-field#post-15865 ) for now.

I think this would be easyish if you started using the storage facade: http://octobercms.com/docs/services/filesystem-cdn#basic-usage

**Comment by mabehiry** [comment]
The same problem.
Any update about this?

**Comment by matteotrubini** [comment]
If anyone can open a PR I would be happy to review and merge it.

**Comment by DieterHolvoet** [comment]
I created a [simple image resize plugin](https://github.com/DieterHolvoet/oc-imageresizer-plugin) inspired by this one, with support for all kinds of storages. For now quite barebones, might add settings and more features later. If someone wants to try to fix this issue, you could have a look at my code.

**Comment by matteotrubini** [comment]
@DieterHolvoet the reason for your "fork" was only the support for Flysystem?
If yes, I would be really happy to merge a PR! Otherwise I would like to know the other reasons to have your POV.

**Comment by DieterHolvoet** [comment]
I started out trying to fix the code of this plugin, but after a while I decided it would be easier to just rewrite the whole thing. I haven't created a PR because my version is missing a couple of features this plugin has and I don't really need, like settings and TinyPNG support. I might add those if I have the time, and if I do I'll create a PR.

**Comment by matteotrubini** [comment]
This plugin is being migrated to core (see #55), so we are trying to figure out what issues are still relevant to invite to reopen them in core.

Issues that will remain inactive in next 30 days will be closed.
